name = "Morphism"
license = "MIT"
licenselink = "https://github.com/shawnohare/hugo-morphism/blob/master/LICENSE.md"
description = "A minimalist blog theme with mathematical typesetting support."
homepage = "http://github.com/shawnohare/hugo-morphism"
tags = ["blog", "morphism", "minimal"]
features = ["math", "pure.css"]
min_version = 0.15

[author]
  name = "Shawn O'Hare"
  homepage = "https://shawnohare.com"
