contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = true 
baseurl = "http://"
canonifyurls = true
theme = "morphism"
title = "Hugo Morphism Theme Example"

[taxonomies]
  category = "categories" 
  group = "groups"
  series = "series"
  tag = "tags"

[params]
  subtitle = "A Cool Subtitle"
  copyrightHolder = "Copyright Holder"
  showPoweredBy = true

# -----------------------------------------------------------------------
# Morphism theme navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fa fa-book fa-lg'></i> "
  weight = -100 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Categories"
  pre = "<i class='fa fa-tags fa-lg'></i> "
  weight = -90 
  identifier = "categories"
  url = "/categories"
[[menu.nav]]
  name = "Me"
  pre = "<i class='fa fa-user fa-lg'></i> "
  weight = -80
  identifier = "me"
  url = "/page/about/"

# -----------------------------------------------------------------------
# Morphism theme footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-github fa-2x'></i> "
  weight = -100 
  identifier = "github"
  url = "https://github.com"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-twitter fa-2x'></i> "
  weight = -99 
  identifier = "twitter"
  url = "https://twitter.com"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-envelope fa-2x'></i> "
  weight = -98 
  identifier = "mail"
  url = "mailto:"
