contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = true 
baseurl = "http://"
canonifyurls = true
theme = "morphism"
title = "Hugo Morphism Theme Example"

[taxonomies]
  category = "categories" 
  group = "groups"
  series = "series"
  tag = "tags"

[params]
  subtitle = "A Cool Subtitle"
  copyrightHolder = "Copyright Holder"
  showPoweredBy = true
  listPaginatorLimit = 3337 

# -----------------------------------------------------------------------
# Morphism theme navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "home"
  pre = ""
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "posts"
  pre = ""
  weight = -100 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "categories"
  pre = ""
  weight = -90 
  identifier = "categories"
  url = "/categories"
[[menu.nav]]
  name = "tags"
  pre = ""
  weight = -89 
  identifier = "tags"
  url = "/tags"
[[menu.nav]]
  name = "me"
  pre = ""
  weight = -80
  identifier = "me"
  url = "/page/about/"

# -----------------------------------------------------------------------
# Morphism theme footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = "GitHub"
  pre = ""
  weight = -100 
  identifier = "github"
  url = "https://github.com"
[[menu.footer]]
  name = "Twitter"
  pre = ""
  weight = -90 
  identifier = "twitter"
  url = "https://twitter.com"
[[menu.footer]]
  name = "LinkedIn"
  pre = ""
  weight = -80 
  identifier = "linkedin"
  url = "https://www.linkedin.com"
[[menu.footer]]
  name = "Mail"
  pre = ""
  weight = -70 
  identifier = "mail"
  url = "mailto:"
